# Generated by Django 4.2.7 on 2025-12-28 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scrapedarticle',
            table=None,
        ),
    ]
